#!/bin/bash
#--------------------------------------------------------
#   Don't remove this section for credits
#   Don't rename this file
#--------------------------------------------------------
#   If you use some codes frome here, please give credit to www.helmiau.com
#--------------------------------------------------------
#   Script by Helmi Amirudin a.k.a helmiau
#   my profile page https://wwww.helmiau.com
#   my github https://github.com/helmiau
#--------------------------------------------------------

#--- Warna Warna
R='\033[1;31m' # Merah Muda
G='\033[1;32m' # Hijau Muda
Y='\033[1;33m' # Kuning
N='\033[1;37m' # Putih
SCRIPTVER="26-02-2023"
SCRIPTNAME="$(basename "$0")"
URLX="https://github.com/helmiau/helmiwrt-packages/releases/download/ipk"

if [[ $1 == *".ipk"* ]]; then
	[ -f /root/$1 ] && rm "$1"
	wget --no-check-certificate "$URLX"/"$1" -O /root/"$1"
	[ -f /root/$1 ] && opkg update && opkg install /root/"$1" && rm "$1"
elif [[ $1 == "-fd" ]] && [[ $2 == *".ipk"* ]]; then
	[ -f /root/$2 ] && rm "$2"
	wget --no-check-certificate "$URLX"/"$2" -O /root/"$2"
	[ -f /root/$2 ] && opkg update && opkg install --force-depends /root/"$2" && rm "$2"
elif [[ $1 == "-dl" ]] && [[ $2 == *".ipk"* ]]; then
	[ -f /root/$2 ] && rm "$2"
	wget --no-check-certificate "$URLX"/"$2" -O /root/"$2"
elif [[ $1 == "-l" ]]; then
	echo -e "${R}======================================================${N}"
	echo -e "      ${Y}Lists of available HelmiWrt Packages IPK"
	echo -e "${R}======================================================${N}"
	curl -sL https://api.github.com/repos/helmiau/helmiwrt-packages/releases/tags/ipk | grep 'browser_download_url' | awk -F '"' '{print $4}' | sed 's|^.*ipk/||g'
	echo -e "${R}======================================================${N}"
	echo -e " ${Y}Read installation steps by run ${G}$SCRIPTNAME${Y} command"
	echo -e "${R}======================================================${N}"
else
	echo -e "${R}======================================================"
	echo -e "   ${G}HelmiWrt Packages Command Lists by Helmi Amirudin"
	echo -e "              ${Y}Script Version : ${G}$SCRIPTVER"
	echo -e "${R}======================================================${N}"
	echo -e "  Run ${G}$SCRIPTNAME -l ${N}to read lists of available ipks"
	echo -e "     ex: ${G}$SCRIPTNAME -l${N}"
	echo -e "  Run ${G}$SCRIPTNAME luci-app-name_v999.ipk ${N}to install ipk"
	echo -e "     ex: ${G}$SCRIPTNAME luci-app-tinyfm_1.6_all.ipk${N}"
	echo -e "  Run ${G}$SCRIPTNAME -fd luci-app-name_v999.ipk ${N}to force install ipk"
	echo -e "     ex: ${G}$SCRIPTNAME -fd luci-app-tinyfm_1.6_all.ipk${N}"
	echo -e "  Run ${G}$SCRIPTNAME -dl luci-app-name_v999.ipk ${N}to download ipk only"
	echo -e "     ex: ${G}$SCRIPTNAME -dl luci-app-tinyfm_1.6_all.ipk${N}"
	echo -e "${R}======================================================${N}"
fi
