#
# OpenSpeedtest Software made by Lutfa Ibtihaji <http://openspeedtest.com/>
# LuCI OpenSpeedtest App by Helmi Amirudin <https://www.helmiau.com>
#
# Copyright (C) 2021 Helmi Amirudin <https://www.helmiau.com>
# This is free software, licensed under the Apache License, Version 2.0
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI OpenSpeedtest App
LUCI_PKGARCH:=all
PKG_NAME:=luci-app-openspeedtest
PKG_VERSION:=1.0
PKG_RELEASE:=1

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature