#!/bin/sh /etc/rc.common
START=11
[ -n "${IPKG_INSTROOT}" ] && return 0
grep(){
	/bin/busybox 'grep' $@
}
for i in $( ls /sys/class/net/*/device/uevent | awk -F'/' '{print $5}' | tr '\n' ' ' );
do	
	mac_addr=$( grep $i /etc/config/mactoiface | awk '{print $3}' | tr -d '"' )	
	if [ "$mac_addr" != '' ]; then			
		ip link set "$i" down 		
		ip link set "$i" name old"$i"			
	fi
done
for i in $( ls /sys/class/net/*/device/uevent | awk -F'/' '{print $5}' | tr '\n' ' ' );
do
	mac_addr=$( cat /sys/class/net/$i/address  )	
	iface_name=$( grep -i $mac_addr /etc/config/mactoiface | awk '{print $2}' )	
	if [ "$iface_name" != '' ]; then			
		ip link set "$i" down 		
		ip link set "$i" name "$iface_name"			
	fi
done
